import React from "react"

class YokaiWatch2019 extends React.Component {
    render() {
        return (<>
            <div class='content'>
                <div class='line-break' />

                <h4>1. Introduction</h4>
                <p>The sudden and immense popularity of <i>Yo-kai Watch</i> (妖怪ウォッチ), a 2013 media franchise, caught the Japanese public by surprise—parents scrambled to buy toys in sold-out stores, manufacturers struggled to meet demand, and even the franchise’s creators themselves, according to its studio and publisher Level-5’s chief executive, were stunned by its runaway success (Famitsu). But the franchise’s success seems logical, almost inevitable, when considering the recipe that Level-5 followed—one responsible for perennial hits like <i>Pokémon</i> (ポケットモンスター) and <i>Doraemon</i> (ドラえもん), and one that Level-5 extensively researched and perfected to create its consumerist phenomenon (Steinberg 245). Specifically, the strategy called for dispersing the franchise across a diverse portfolio of platforms, virtual and physical—a <i>shōnen manga</i> (少年 漫画) series, a console game, an anime series, a mobile app, a movie, an official dance and a lineup of toys—each serving as a unique point of entry into the franchise as well as a gateway into other platforms, creating a complex yet cohesive “media mix” (Steinberg 247)</p>
                <p>The premise of <i>Yo-kai Watch</i> is quite simple. Amano Keita (天野 景太), a young Japanese boy, accidentally frees a <i>yōkai</i> (妖怪) named Whisper (ウィスパー) from his imprisonment inside a <i>gashapon</i> (ガシャポン) capsule. Whisper gives Keita a “yōkai watch” that can reveal invisible yōkai, and together they solve everyday problems and supernatural mysteries while befriending other yōkai to earn their “yōkai medals.” Each part of this plot has potential for commodification, and Level-5 lets none of it go to waste, packaging them into anime episodes or game quests or purchasable toys. In Steinberg’s view, just as a nation at war may mobilize its entire resources toward the war effort, this media mix can be understood as a total mobilization of all of society’s resources toward the goal of consumption. Therefore, by marshaling the consumptive desires of children, the spending powers of parents, the societal trends of urban Japan and the popular culture of Japanese youth, the media mix of <i>Yo-kai Watch</i> can be viewed as a total social mobilization in the effort to drive consumption and maximize capital (Steinberg 248)</p>
                <p>Such elaborate activities toward capital can be viewed in the vocabulary of magic and sorcery, as endorsed by the philosopher Isabelle Stengers. Since we are discussing an anime about yōkai—those supernatural beings in Japanese tradition that exist outside the rational boundaries of science and religion—such an analogy is especially apt (Figal 42). In this context, capitalism is a “system of sorcery without sorcerers.” Only the invisible hand of market forces can claim to truly control capitalism, though there is no lack of willing “minions,” who follow and enable and facilitate the ideology of capitalism (Pignarre and Stengers 40–41). It is these minions who lure other humans using magical, ever-creative means; once captured, the humans consume, generating profit and accumulating capital for these minions and for the capitalist economy as a whole.</p>
                <p>Steinberg, in his assessment of <i>Yo-kai Watch</i>, seems deeply critical of this sorcery. His disapproval is implicit when he describes the anime as a mere “instructional video” for the media mix setup; when he accuses the franchise of conditioning children for “insidious” gambling and cycles of planned obsolescence; when he compares the total social mobilization to the mobilization of the U.S. military in the Middle East; and when he quotes publishing magnate Kadokawa Haruki (角川 春樹)’s boasts equating his media mix strategy to Adolf Hitler’s Nazism (Steinberg 254). Steinberg, then, describes how the “evil minions” at Level-5 totally mobilized its resources to set lures, capture viewers and accrue profits. Upon closer examination of the anime, however, we see that many aspects of <i>Yo-kai Watch</i> do more than just promote a product. Instead, the media mix of <i>Yo-kai Watch</i>, in its total social mobilization, combines magical lure and capitalist capture to form an immersive, collaborative environment.</p>
                <p>The <i>Yo-kai Watch</i> media mix is, by definition, a sprawling mix of media that spans many platforms, spinoffs and reboots. Even the original 2014 anime, responsible for most of the franchise’s initial popularity, spanned 214 episodes over its 4-year run (Ashcraft). Rather than give a too broad analysis of the entire media mix, we will limit the scope of this essay to a close reading of the anime’s first episode—“Yo-kai Are Real!” (妖怪がいる！) and “The Spooky Intersection” (恐怖の交差点)—which nicely introduces not only the characters and plot but also the media mix strategy itself.</p>

                <h4>2. Capitalist Capture and a Blended Reality</h4>
                <p>As Steinberg writes, <i>Yo-kai Watch</i> uses total social mobilization to advertise its products and encourage children and their parents to consume (246). However, the media mix’s extent of capitalist capture goes beyond mere marketing techniques. Rather, it penetrates deep into the entertainment platforms themselves, as is apparent when the anime ascribes value, implicitly and explicitly, to its purchasable merchandise. In one of the anime’s first scenes, we watch as Keita takes a 100-yen coin (about one U.S. dollar) from his pocket, inserts it into a capsule machine, and turns the crank to finalize the transaction, in a step-by-step, almost tutorial-like sequence. And when Keita is unimpressed with the “prize” that is the yōkai Whisper and demands a refund, Whisper refuses and tells him “that’s how it goes with capsule machines.” In this way, the anime teaches its young viewers how to spend—the franchise operates the same capsule machines in Japan—and primes them to accept the inevitable disappointment from a chance-based purchase. And, by making this act of consumption the catalyst for the show’s premise and existence—without Whisper, Keita would never have met yōkai—the media mix inextricably associates access to its entertainment with spending. The result is the successful capitalist capture of its target audience, who lack the cognitive ability to detect the intents of advertising (Carter <i>et al.</i> 962).</p>
                <p>This example of capsule machines is part of a wider network of cross-platform feedback loops that has enabled the media mix’s success. The anime teaches viewers to use capsule machines, but the capsule machines in real life contain not yōkai but yōkai medals—the symbols of friendship that Keita collects through his social interactions. The medals can be bought and collected by the viewer as well, for use with the yōkai watch toy that features heavily in the anime and is the namesake of the franchise. The medals are also compatible with the Nintendo 3DS, with which the consumer can scan the medals’ QR codes to import yōkai from the real world into the game. The game version is in turn referenced in the end credits of each episode, where the characters are rendered in the 3D style of the 3DS game, as are all purchasable merchandise including the yōkai medals and watch, signaling their commodification.</p>
                <p>Beyond providing just a “connective element between the narrative world and the physical world” (Steinberg 251), the media mix of <i>Yo-kai Watch</i> is a tangled, self-referential web of capture that traps consumers in its vast grasp of <i>mise en abyme</i>, whose elements travel and communicate freely across the 2D and 3D worlds. Therefore, the techniques of capitalist capture entangles all platforms to create a blended reality in which purchased commodities can be shared and enjoyed anywhere, within realities both physical and virtual, in a seamless, consumerist experience.</p>

                <h4>3. Social Lures and Sociality</h4>
                <p>According to the magical interpretation of capitalism, not all people are equally vulnerable to capture. Sometimes, a potential consumer may need to be lured first before he or she can be convinced to consume (Stengers 8), and we see such lures at play in the anime’s promotion of sociality. Navigating the world of <i>Yo-kai Watch</i> is never a solitary endeavor. According to Whisper, yōkai live in a “spooky dimension” that overlaps with the human world; whether Keita can see them or not, they exist everywhere, waiting to be found.</p>
                <p>One such yōkai is Jibanyan (ジバニャン)—the two-tailed cat known as <i>nekomata</i> (猫又)—who has been possessing pedestrians and leading them into traffic, in order to practice fighting cars and avenge his own roadkill death. Banished by his former owner Amy (エミちゃん) who called him a “loser” (ダサ) for dying, and by society after he became invisible to humans as yōkai, Jibanyan is a social outcast. Indeed, he confesses to be extremely lonely, and that possession is the closest he can come to a human connection; after learning his actions are endangering others, he resolves to be alone forever and run away. However, he is stopped by Keita, who prevents Jibanyan from isolating himself further and offers to be his training partner and friend. Through this scene, the anime teaches viewers that social outsiders are to be helped, not ostracized or ignored. More broadly, the anime teaches viewers to interact and be social with others, whether they be humans or yōkai.</p>
                <p>Such promotions of sociality are not mere public service announcements to the Japanese youth. Instead, they are social lures, which aim to attract and retain viewers. By placing Keita in everyday conflicts familiar to children—catching bugs, watching parents fight, or meeting a person (or cat) in need—and letting him work through the steps of resolving them, the anime allows young viewers to empathize with and emulate the main character. And, by constantly reminding viewers that Keita is normal, or <i>futsu</i> (普通), the media mix makes Keita a representative for the hypothetical viewer, who shows by example how to act and what to consume in order to be just like Keita (Ivy 250). And the way to enter his world and socialize with yōkai is by buying the merchandise and collecting the medals and equipping the yōkai watch—in other words, by becoming captured.</p>

                <h4>4. Non-Capitalist Countercurrents</h4>
                <p>These lures are ostensibly meant to aid capitalist capture, but they also have effects that seem not to align with capitalism. Though some claim that economist Adam Smith, known as the “Father of Capitalism” (Bassiry and Jones 626), valued charity and cooperation (Abel 165), his vision of capitalism is still grounded in the assumption that all humans act in their economic self-interest (Werhane 669). So it is surprising when the anime goes against the grain of capitalism and appears to encourage collaboration and sharing.</p>
                <p>We see this in Keita’s previously described interaction with Jibanyan. Initially, Keita reacts with fear, and he reluctantly agrees to help Jibanyan only to stop the “sudden stop incidents.” When Jibanyan resolves to stop possessing humans and “be all on [his] own fur-ever,” Keita’s goal of stopping the accidents would have been satisfied, since Jibanyan starts fleeing the intersection he had been haunting. But Keita stops him and, in an act of altruism that stuns Whisper and touches Jibanyan, offers to let himself be possessed. With no apparent advantage to himself and requesting nothing in return, Keita acts selflessly to share a resource—in this case, his own body—with a yōkai in need, violating the self-interest principle of capitalism. The unexpected reward of Jibanyan’s yōkai medal, the first in Keita’s soon-to-grow collection, confirms this to have been the right choice.</p>
                <p>The yōkai medals, symbols of Keita’s sociality with yōkai, also have unexpectedly non-capitalist effects in the real world—in their merchandise form. The medals’ sales model is similar to those of other collect-’em-all media mixes like <i>Pokémon</i>—the specific medal one gets from a capsule or a store-bought pack is up to chance, and continuous consumption is needed to find all unique medals and build a complete collection. Because the process results in inevitable duplicates, trading with others is an efficient, non-zero-sum method of growing both parties’ collections. Beyond just strategy, such trades may even have been necessary at the height of <i>Yo-kai Watch</i>’s popularity in 2014, when there were chronic shortages of the franchise’s toys in Japan (Ashcraft, 2014). Though difficult to verify—no paper trail is created when two children swap yōkai medals—the presence of the online Reddit community <a href="https://www.reddit.com/r/yokaiwatch/">r/YokaiSwap</a>, dedicated to such exchanges (Reddit, 2015), suggests these trades must have occurred offline as well. In any case, these informal trading systems form unofficial barter economies, facilitated not by the “minions” of capitalism but by the consumers themselves. By relying on non-monetized exchanges rather than financial transactions, these economies exist outside the intended capitalist economy and, depending on its scale, may even work against it by depressing official sales.</p>
                <p>To the cynic, these non-capitalist effects may seem like yet more examples of magical lures. The promotion of collaboration and an alternative economy of merchandise may assuage parents and the larger society, who may be concerned about the media mix’s rampant consumerism, luring them into a false sense of security and rendering them—and, by extension, their children—vulnerable to capture (Pignarre and Stengers 42). However, even if such effects are intentional, they are still significant for the impact they have on their audience. Exposed to a countercurrent against capitalism, the young viewers and their parents may hopefully learn to recognize the operations of capitalism and to protect oneself against it if necessary (Pignarre and Stengers 45).</p>

                <h4>5. Conclusion</h4>
                <p>At first glance, it can be easy to dismiss the anime of the <i>Yo-kai Watch</i> media mix as “‘30-minute commercials’ or ‘program-length commercials,’” designed to sell products to an unwitting audience (Steinberg 244). While partially true, a magical interpretation of capitalism allows us to understand the inner workings of such a strategy. By entangling all available platforms—anime, game, merchandise and more—in a self-referential web of capitalist capture, the media mix creates out of physical and virtual worlds a blended reality, in which children can be taught to spend and compelled to consume. To aid in this capture, the media mix also deploys social lures, which encourage sociality with yōkai and let viewers immerse themselves into the character and world of Keita.</p>
                <p>However, these lures in <i>Yo-kai Watch</i> have unexpectedly non-capitalist effects, as the promotion of sociality gives way to the encouragement of collaboration and sharing. And the collection of yōkai medals—those symbols of sociality and testaments to friendship with other yōkai—leads to the rise of alternative barter economies that compete with and even subvert the official capitalist system. When the manga–game–anime–toy media mix of <i>Yo-kai Watch</i> was first released in 2014, it completely consumed Japan, creating queues and shortages and sold-out stores. In our consumerist and commodified era of media mixes, detecting such non-capitalist countercurrents may allow us to become more aware and protect ourselves from the sorcery of capture and lures and capitalism.</p>
            </div>
        </>)
    }
}

export default YokaiWatch2019
